### PR TITLE
Feature: skip connectivity checks

### PR DESCRIPTION
**Pull request by andreasschulze**
Hello,

I intend to test _many_ domains.  I added an option to skip the connectivity checks because I'm sure I _do have_ connectivity.
If you reject the PR, I'm interested in why it is nessesary to test 12 services again and again.

Thanks for sharing this software
Andreas

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by paulf69487623** [comment]
Hey Andreas,

Thanks for the PR.  The code itself looks fine, and I'm not opposed to merging it.  I am curious though - the connectivity check happens only once at startup and only takes a few seconds.  We regularly scan > 10k zones in a single run.  You can either specify multiple files on the command line, or pipe in a list using the --stdin option.

Thanks,

Paul

**Comment by andreasschulze** [comment]
my use-case is more "one shot per domain". That's fix for other reasons. I Agree, testing many domains in one run is better and does not require to skip the connectivity checks.

**Comment by andreasschulze** [comment]
challenge accepted :-) but that may take some days ...

**Comment by andreasschulze** [comment]
was easier then expected ...

see this diff: https://github.com/yahoo/SubdomainSleuth/compare/master...andreasschulze:skip_connectivity_check_2?expand=1

I renamed skip-resolver-check to force-resolver-check. This make the naming more consistent and the code was similiar for all 3 cases. The diff looks "so large". At the end it's only
```
if force_foo {
  <existing code intended by one TAB>
} else {
  <logging>
  <var = true>
}

What do you think?

Andreas

**Comment by andreasschulze** [comment]
I would delay a new pull request untill there are no further comments

**Comment by paulf69487623** [comment]
Hey Andreas,

I was thinking more of a tri-state flag, where it can be unset (test connectivity), true (force to true), or false (force to false).  I thought you could do this with a normal BoolVar and a pointer, but it doesn't look like that works.  I put together the example below that would let us do what we want.  The TriFlag type has an IsSet bool and a Value bool.  If the flag isn't set, you can use the existing logic.  If the flag is set, you can skip the connectivity check and use the value provided.

There are some libraries that have similar code, but I'd rather not add a dependency for a single near-trivial block of code.

```
package main

import (
	"flag"
	"fmt"
)

type TriFlag struct {
	IsSet bool
	Value bool
}

// Parse the value for the flag.  String values for true/false come from the
// godocs for flag.Bool.  If a value is provided, it must match one of the true
// or false values.
func (tf *TriFlag) Set(value string) error {
	for _, t := range []string{"1", "t", "T", "true", "TRUE", "True"} {
		if value == t {
			tf.IsSet = true
			tf.Value = true
		}
	}

	for _, f := range []string{"0", "f", "F", "false", "FALSE", "False"} {
		if value == f {
			tf.IsSet = true
			tf.Value = false
		}
	}

	if tf.IsSet {
		return nil
	}

	return fmt.Errorf("Invalid boolean value")
}

func (tf *TriFlag) String() string {
	return fmt.Sprintf("TriFlag(%v, %v)", tf.IsSet, tf.Value)
}

func main() {
	var tf TriFlag
	flag.Var(&tf, "force", "Force?")

	flag.Parse()

	fmt.Printf("Force?  %v\n", tf)
}
```

**Comment by andreasschulze** [comment]
Things change! I thought again about your "We regularly scan > 10k zones in a single run" and found a way to do this in my setup, too. So the main reason to skip something is gone. I'm fine with discarding this PR. (unsure, what's best wording for what ever you have to do ...)

I think better you should leave subdomainsleuth as simple as it is for now. Adding code always open potential to add "unintended features". If others see this work useful, it's documented here anyway...

**Comment by paulf69487623** [comment]
No recent activity here, so closing this out.

**Pull request closed without merging**
