### PR TITLE
if no '--resolver' is given, try to extract resolvers from /etc/resolv.conf

### PR DESCRIPTION
**Pull request by jschauma**
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by paulf69487623** [comment]
Hey Jan,

Thanks for the contribution!  Have you looked at the ClientConfig type and the ClientConfigFromFile function from the miekg/dns library?  It looks that can parse /etc/resolv.conf and the list of servers is available in the struct.

https://pkg.go.dev/github.com/miekg/dns#ClientConfig

I'm happy to merge this as is if the functionality there doesn't do what you need.

Thanks,

Paul

**Comment by jschauma** [comment]
Paul F ***@***.***> wrote:

> https://pkg.go.dev/github.com/miekg/dns#ClientConfig

That seems useful.  I'll take a look and will let you
know.

**Comment by jschauma** [comment]
Hahaha, so `clientConfigFromFile` almost literally does the same thing that my code did (scanner, split fields, match "namservers").  So this diff now uses that code.  All around not much of a win one way or another.  Pick whichever you like better. :-)

**Review by paulf69487623 — APPROVED** [review]
LGTM!

**Pull request merged**
